authors:
  digitalgrease:
    name: digitalgrease
    description: Engineer | Hacker | Maker — writing about high tech, low tech, and the intersection thereof.
    avatar: https://github.com/digital-grease.png
    url: https://digitalgrease.dev
